# Generated by Django 3.2.16 on 2023-01-28 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smartphones', 'Smartphones'), ('Smartwatches', 'Smartwatches'), ('Earphones', 'Earphones'), ('Camera', 'Camera'), ('TV', 'Tv'), ('AC', 'Ac')], default='Laptop', max_length=20)),
                ('brands_count', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0, message='Cannot be less than 0'), django.core.validators.MaxLengthValidator(14, 'Can not be more than 14')])),
                ('image', models.ImageField(upload_to='product/images/%Y/%m/%d/')),
                ('meta_data', models.FileField(upload_to='product/files/%Y/%m/%d/')),
            ],
        ),
    ]
