# Generated by Django 3.2.16 on 2023-01-28 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Cannot be less than 0'), django.core.validators.MaxValueValidator(14, 'Can not be more than 14')]),
        ),
    ]
