# Generated by Django 3.2.16 on 2023-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_product_brands_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='brand/images/%Y/%m/%d/')),
                ('meta_data', models.FileField(upload_to='brand/files/%Y/%m/%d/')),
            ],
        ),
    ]
