# Generated by Django 3.2.16 on 2023-03-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.CharField(default='Laptop', max_length=20),
        ),
    ]
