# Generated by Django 3.2.16 on 2023-03-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reviewlaptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewLaptop',
        ),
    ]
