# Generated by Django 3.2.16 on 2023-03-07 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('availability', models.BooleanField()),
                ('type', models.CharField(default='None', max_length=20)),
                ('Screen', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(10, message='Cannot be less than 10'), django.core.validators.MaxValueValidator(20, 'Can not be more than 20')])),
                ('screenResolution', models.CharField(choices=[('1024 x 600', 'Choice1'), ('1366 x 768', 'Choice2'), ('1600 x 900', 'Choice3'), ('1920 x 1080', 'Choice4'), ('2560 x 1440', 'Choice5'), ('3200 x 1800', 'Choice6'), ('3840 x 2160', 'Choice7')], default='1920 x 1080', max_length=15)),
                ('cpubrand', models.CharField(default='None', max_length=15)),
                ('cpumodel', models.CharField(default='None', max_length=15)),
                ('cpucores', models.CharField(default='Quad Core', max_length=10)),
                ('cpugeneration', models.CharField(default='None', max_length=20)),
                ('cpuspeed', models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(1.5, message='Cannot be less than 1.5'), django.core.validators.MaxValueValidator(6, 'Can not be more than 6')])),
                ('harddiskrpm', models.PositiveIntegerField(max_length=6, validators=[django.core.validators.MinValueValidator(1000, 'Cannot be less than 1000'), django.core.validators.MaxValueValidator(10000, 'Cannot be greater than 10000')])),
                ('hardisk', models.PositiveSmallIntegerField()),
                ('byte_type_for_harddisk', models.CharField(choices=[('TB', 'Choice1'), ('GB', 'Choice2'), ('MB', 'Choice3')], default='GB', max_length=3)),
                ('ram', models.PositiveSmallIntegerField()),
                ('byte_type_for_graphics', models.CharField(choices=[('TB', 'Choice1'), ('GB', 'Choice2'), ('MB', 'Choice3')], default='GB', max_length=3)),
                ('graphics', models.PositiveSmallIntegerField()),
                ('backlit_keyboard', models.BooleanField()),
                ('hdmi', models.BooleanField()),
                ('optical_drive', models.BooleanField()),
                ('check_ssd', models.BooleanField()),
                ('byte_type_for_ssd', models.CharField(choices=[('TB', 'Choice1'), ('GB', 'Choice2'), ('MB', 'Choice3')], default='GB', max_length=3)),
                ('ssd', models.PositiveSmallIntegerField()),
                ('usb_3', models.BooleanField()),
                ('count_usb_3', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, 'Cannot be greater than 3')])),
                ('usb_type_c', models.BooleanField()),
                ('count_usb_type_c', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3, 'Cannot be greater than 3')])),
                ('figerprints', models.BooleanField()),
                ('anti_glare_screen', models.BooleanField()),
                ('face_recognition', models.BooleanField()),
                ('os', models.CharField(choices=[('Android', 'Choice1'), ('Chrome', 'Choice2'), ('DOS', 'Choice3'), ('Linux', 'Choice4'), ('Mac', 'Choice5'), ('Ubuntu', 'Choice6'), ('Windows 10', 'Choice7'), ('Windows 11', 'Choice8'), ('Windows 7', 'Choice9'), ('Windows 8', 'Choice10'), ('Windows', 'Choice11'), ('Others', 'Choice12')], default='Others', max_length=10)),
                ('backup_battery', models.PositiveSmallIntegerField(max_length=2, validators=[django.core.validators.MaxValueValidator(15, 'Cannot be greater than 15')])),
                ('weight', models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(0.5, 'Cannot be less than 0.5kg'), django.core.validators.MinValueValidator(4, 'Cannot be greater than 4kg')])),
                ('warranty', models.PositiveSmallIntegerField(max_length=1, validators=[django.core.validators.MaxValueValidator(6, 'Cannot be greater than 6')])),
                ('image', models.ImageField(upload_to='laptop/images/%Y/%m/%d/')),
                ('meta_data', models.FileField(upload_to='laptop/files/%Y/%m/%d/')),
                ('ratings', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Cannot be less than 0'), django.core.validators.MaxValueValidator(5, 'Can not be more than 5')])),
                ('count_ratings', models.PositiveSmallIntegerField()),
                ('spec_score', models.PositiveSmallIntegerField()),
                ('everyday_type', models.BooleanField()),
                ('gaming_type', models.BooleanField(default=False)),
                ('business_type', models.BooleanField(default=False)),
                ('performance_type', models.BooleanField()),
                ('release_date', models.DateField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.product')),
            ],
        ),
    ]
