# Generated by Django 3.2.16 on 2023-03-07 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='backup_battery',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15, 'Cannot be greater than 15')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='harddiskrpm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000, 'Cannot be less than 1000'), django.core.validators.MaxValueValidator(10000, 'Cannot be greater than 10000')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='warranty',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6, 'Cannot be greater than 6')]),
        ),
    ]
