# Generated by Django 3.2.16 on 2023-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_auto_20230307_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
