# Generated by Django 3.2.16 on 2023-03-07 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_alter_laptop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='check_hardisk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='touch_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='byte_type_for_graphics',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], default='GB', max_length=3),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='byte_type_for_harddisk',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], default='GB', max_length=3),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='byte_type_for_ssd',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], default='GB', max_length=3),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='harddiskrpm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000, 'Cannot be greater than 10000')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(choices=[('Android', 'Android'), ('Chrome', 'Chrome'), ('DOS', 'DOS'), ('Linux', 'Linux'), ('Mac', 'Mac'), ('Ubuntu', 'Ubuntu'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows', 'Windows'), ('Others', 'Others')], default='Others', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screenResolution',
            field=models.CharField(choices=[('1024 x 600', '1024 x 600'), ('1366 x 768', '1366 x 768'), ('1600 x 900', '1600 x 900'), ('1920 x 1080', '1920 x 1080'), ('2560 x 1440', '2560 x 1440'), ('3200 x 1800', '3200 x 1800'), ('3840 x 2160', '3840 x 2160'), ('2560 X 1600', '2560 X 1600')], default='1920 x 1080', max_length=15),
        ),
    ]
