# Generated by Django 3.2.16 on 2023-03-07 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_auto_20230307_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(0.5, 'Cannot be less than 0.5kg'), django.core.validators.MaxValueValidator(4, 'Cannot be greater than 4kg')]),
        ),
    ]
