# Generated by Django 3.2.16 on 2023-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0005_alter_laptop_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='check_graphics_details',
            field=models.BooleanField(default=False),
        ),
    ]
