# Generated by Django 3.2.16 on 2023-03-07 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0006_laptop_check_graphics_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='backup_battery',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Cannot be less than 0'), django.core.validators.MaxValueValidator(24, 'Cannot be greater than 15')]),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(default=1.2, validators=[django.core.validators.MinValueValidator(0.5, 'Cannot be less than 0.5kg')]),
        ),
    ]
