# Generated by Django 3.2.16 on 2023-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0007_auto_20230307_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
