# Generated by Django 3.2.16 on 2023-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0010_alter_laptop_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(choices=[('Android', 'Android'), ('Chrome', 'Chrome'), ('DOS', 'DOS'), ('Linux', 'Linux'), ('Mac OS', 'Mac OS'), ('Ubuntu', 'Ubuntu'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows', 'Windows'), ('Others', 'Others')], default='Others', max_length=10),
        ),
    ]
